name: Sample Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Test and Upload report to TestOps
      run: mvn clean test -Dtestops.apiKey=${{ secrets.TESTOPS_API_KEY }} -Dtestops.projectId=${{ secrets.TESTOPS_PROJECT_ID }}
